apiVersion: v1
kind: Secret
metadata:
    name: db-password-secret
    namespace: project
data:
    db_password: ENC[AES256_GCM,data:npKkkqOsu0OclRu7,iv:eItVUvZ9cIWxlySBo1sZxYdpal5AV5ZEhT8u53kUUV8=,tag:EbpSJbjmGJqXiXT7aA6ymQ==,type:str]
sops:
    age:
        - recipient: age1v427y46egcxw7xxxmj96k5wjvrsshfsykpz5eaepzq56hu8p85hs58za28
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDNUJkMjVna1FadnFXZlZU
            ZUVoU0l2ZjZoc2FlUW82RHIzRlE3TU9xdVVNClNlczl2Nk5SSnY0djNrTVV4VlQ1
            cjlUNTVYTmlhbHBYd0szREhzWXQrd1kKLS0tIHVxVzdLUWxpRFNyVi9VWDBuTW0z
            M3BHcGZYNm1zeFF1N3JTdVZ6b214VzQKGv+86LUEg1MOQGsG1Io4q30xcL1uTXv9
            QeMeZMHy5qLUjcV6jtVaP3Wybd46P5fQNRMc/otLY6C0AIcTIi57hA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-14T22:33:11Z"
    mac: ENC[AES256_GCM,data:jfCOs1BF8lD+/mXYm1JeZ9Gwqv/Try8jZodg/+B2mGLvaEtA0c69jhM/dVF3uYi2otttMLyHesPBLYkHUTLjx3wylSg8rRbfWHONdPDeRAJ+JaN4jFbnEV8Gq9pwDEJZvYqExE8IOe6T44J2bozHVwO6f4OPacjnqHvREsU88e0=,iv:nlJAXGGJoX/vuKdTzpVLrnmNTFHF5Mt52vjUCJeIit8=,tag:dJJBJRqS6/C+nCeZgEZXjg==,type:str]
    encrypted_regex: ^(data)$
    version: 3.10.2
