apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namePrefix: staging-
images:
- name: PROJECT/IMAGE_DIR1
  newName: europe-north1-docker.pkg.dev/dwk-gke-467121/my-repository/todo-app
  newTag: main-6f6f6fb3a10e9c45b9eac8a3dffdc08bcddb853b
- name: PROJECT/IMAGE_DIR2
  newName: europe-north1-docker.pkg.dev/dwk-gke-467121/my-repository/todo-backend
  newTag: main-6f6f6fb3a10e9c45b9eac8a3dffdc08bcddb853b
