apiVersion: v1
kind: Secret
metadata:
    name: db-password-secret
    namespace: project
data:
    #ENC[AES256_GCM,data:bK43AXMk99QE2OtL3g==,iv:yYCgKE6J4p52xL0MhQRJ9kXoICwWWd1wZTQbWjTGAFs=,tag:uQ8kFUCPIuJh02Mq1lPTPA==,type:comment]
    db_password: ENC[AES256_GCM,data:XtxokBsvBJQ4deAQ,iv:F0CzzZj/oAdpOLbul4d0j8in/Fl55iUh1nXVlpNQFpM=,tag:1dipHbLCyVVchhPTz2oinw==,type:str]
sops:
    age:
        - recipient: age1v427y46egcxw7xxxmj96k5wjvrsshfsykpz5eaepzq56hu8p85hs58za28
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwQmx1eGZNM2EvdHNTazc3
            WVN2b3h6Z3RzNm0rQmV2R2dqZi9Uakd4MUFvCk9hYjZBODd5VkhzMVY5Z0t5dkxm
            QlBJWVNHQVhIQkhOcjBFcFJ1MWlpamsKLS0tIDlPSEdlZW1UVDZUVHR3M0cwZ2VB
            bXZteG5vRjZLR1lRbkRJZGRmOGlqR3MK4zaLD+JPb6iLunDaTSz0bdpiORGHw/fE
            arFC+ChMYQ8O9teMErsjpt3LBPjIh4WEt/3qOIEnZGN2OsbRip37MQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-07T20:49:56Z"
    mac: ENC[AES256_GCM,data:pg+OCwXtB0rpA18K9T059t2JC7BNTbEDoepxrvZc7XOgXcebsrl5q9EiLhxPBScmIzGbn4xQkKhCfHV83fGjd79CA5YJEabhbPs9AuekNwJhPEPrKLiCd1i4+jchBZBdKbPUiDQD1rXZQK87swjnsd2iSC1xtyyxLTRS42nssX0=,iv:K3KcWFKtqzI7+XYesjUv0LGmK87i+F/aBUgBRxnTup4=,tag:qUCxT8e6DhK17ti8us7SFQ==,type:str]
    encrypted_regex: ^(data)$
    version: 3.10.2
