apiVersion: v1
kind: Secret
metadata:
    name: db-password-secret
data:
    db_password: ENC[AES256_GCM,data:1pSm5UBZQdlhurEK,iv:TfbB5Sry0aBnB8VYCtAwOWJZjFxOdWkS3Gfpnmdynsc=,tag:BL73PE8wjHaBzpCEPlYKuQ==,type:str]
sops:
    age:
        - recipient: age1v427y46egcxw7xxxmj96k5wjvrsshfsykpz5eaepzq56hu8p85hs58za28
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNMnN1T1hreThoSEVSR2Ro
            Slpjem1FbDI1YmdJMEdOWHJXSzdCL0lFamk4CnhOcU1wcjM1SE9wTmlkTmlIbE1i
            Z3FaWWlOREJ4SXRoYkdFTENXcUFvVlUKLS0tIDN0TjMvUWtkc21rVUVVZnkyTnY3
            akpjY1lwWEZ5NjZPeVBGenR4ODRCTXcKn0tdSuq3ooRHvhK+dHd3UhQF8z5GMm5o
            ovpeEe63h33Ekd13DYKCbfq5K3OK5SbcqOgn4Gh5SyizBx+YsKEtPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-07T22:35:02Z"
    mac: ENC[AES256_GCM,data:dRoI/s35jHus0p4CXAWZ5i3kY0t3gmBEesu7r1I+fe6T54T0lInv1g/3+x1nJzV3rwh2nn6Sgzak/CuAPTbByY2msag+nk+rHP89ZSp1Eb5d8msa6kmrTQMNOmfrBaNxzjq/wcFOe9uvZaty2O7W3raxWmeTaUDcWnutE96mc8Q=,iv:PrhkZdQktRm3TEQolvniqn1nBDs3V6Wyp/PJI4s3GEg=,tag:lqWkQODkB2utyFVk6DTgWA==,type:str]
    encrypted_regex: ^(data)$
    version: 3.10.2
