apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
- ../../../base/
namePrefix: staging-
images:
- name: PROJECT/IMAGE_DIR1
  newName: europe-north1-docker.pkg.dev/dwk-gke-467121/my-repository/todo-app
  newTag: main-6b9d509c99840e76454661d376542d439a8cd90e
- name: PROJECT/IMAGE_DIR2
  newName: europe-north1-docker.pkg.dev/dwk-gke-467121/my-repository/todo-backend
  newTag: main-6b9d509c99840e76454661d376542d439a8cd90e
