apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- persistentvolumeclaim.yaml
- statefulset.yaml
- secret.yaml
- configmaps.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- cronjob.yaml
images:
- name: PROJECT/IMAGE_DIR1
  newName: europe-north1-docker.pkg.dev/dwk-gke-467121/my-repository/todo-app
  newTag: main-6b2f4225682e881125574b2924c732ee7ec3fe32
- name: PROJECT/IMAGE_DIR2
  newName: europe-north1-docker.pkg.dev/dwk-gke-467121/my-repository/todo-backend
  newTag: main-6b2f4225682e881125574b2924c732ee7ec3fe32
