name: Delete Kubernetes Namespace

on:
  delete:

env:
  GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b
  REGISTRY: europe-north1-docker.pkg.dev

jobs:
  delete-namespace:
    runs-on: ubuntu-latest
    environment: project-env-1
    if: github.event.ref_type == 'branch'

    steps:
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          project_id: ${{ env.GKE_PROJECT }}
          location: ${{ env.GKE_ZONE }}

      - name: What is the branch?
        run: |
          echo "${{ github.event.ref }}"

      # main branch cannot be deleted
      - name: Delete Kubernetes namespace
        run: |
          BRANCH="${{ github.event.ref }}"
          if [ "$BRANCH" = "main" ]; then
            echo "main branch (project namespace) cannot be deleted"
            exit 0
          fi

          kubectl delete namespace "$BRANCH" --ignore-not-found=true
